### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by MaxWasUnavailable** [subrotokumar/kurumi#4]
Hi there! Great looking app, very nice to use!

I found two spelling errors. One was in the login warning pop up, "register" is misspelled there (resister iirc?).

The other is in settings, under General: "Experimental" is misspelled as "Experimantal".

Once again, loving the app! Very smooth, and very easy to use overall. Much more intuitive list than most other apps, too!

**Comment by MaxWasUnavailable** [comment]
Here is the first spelling error:
https://github.com/subrotokumar/kurumi/blob/main/lib/features/login/login.dart#L192

**Comment by MaxWasUnavailable** [comment]
And here is the second:
https://github.com/subrotokumar/kurumi/blob/main/lib/features/settings/settings.dart#L221

**Comment by subrotokumar** [comment]
Thank you for taking the time to open the issue regarding the spelling mistakes in our project. Your attention to detail and willingness to contribute to the project's quality is truly appreciated.

If you come across any more issues or have suggestions for further enhancements, please don't hesitate to let us know. Your contributions play a significant role in shaping the project's success.

The changes have been committed and pushed to the project repository => [Commit](https://github.com/subrotokumar/kurumi/commit/c661c50)
These changes will be reflected in the upcoming version update following **v1.3.30-beta**.
