### ISSUE TITLE
bug in profile section 

### ISSUE THREAD

**Issue by anandpanda** [subrotokumar/kurumi#9]
![Screenshot_2024-01-19-09-14-55-727_com.subrotokumar.kurumi.jpg](https://github.com/subrotokumar/kurumi/assets/148877270/97c2ffc3-a347-46b0-af72-3dbc5ebc5d53)

![Screenshot_2024-01-19-09-15-01-700_com.subrotokumar.kurumi.jpg](https://github.com/subrotokumar/kurumi/assets/148877270/f9493232-aee0-4d3d-aef5-bd7531d62c43)

![Screenshot_2024-01-19-09-14-59-142_com.subrotokumar.kurumi.jpg](https://github.com/subrotokumar/kurumi/assets/148877270/44f93d33-4f00-4922-a0b0-5f51bb3cfdfb)

**Comment by subrotokumar** [comment]
Can you confirm if the issue still persists? Also, it would be helpful if you could set your profile to public for better inspection of the problem.

You may attempt to resolve the issue by clearing the app data and reinstalling the application. Additionally, you can clear the cookies of Anilist from your browser before attempting to use the application again. Please let me know if the issue persists.

**Comment by anandpanda** [comment]
I did all that as you said just now.
the issue is still there.

**Comment by subrotokumar** [comment]
![image](https://github.com/subrotokumar/kurumi/assets/95968368/0f4fa3dd-636c-421e-9baf-4b7a5a74462f)

I checked your profile on Anilist. Currently, there are no anime, manga, or characters marked as favorites, which is why you can't find any entries on your profile screen. It's important to note that even after adding something as a favorite, it may take around 6 hours for the changes to reflect.

I think this answered your issue.  Let me know, and I will close this matter.

**Comment by anandpanda** [comment]
Ohh, I really didn't knew that those were for favourites.
I really apologize for the inconvenience.
🙏

**Comment by subrotokumar** [comment]
Please continue to share any other issues, ideas or suggestions you might have. My aim is to create an app that's both functional and user-friendly, and your contribution plays a significant role in achieving that goal.

**Comment by anandpanda** [comment]
hello again!!

i have a request

your repository is now also included in my repositories

can you please remove me as a collaborator

i think when i raised a issue, i got promoted to a collaborator.

i only want to view my repositories which i worked on.

hope you'll help

**Comment by subrotokumar** [comment]
It seems you're asking to be removed as a collaborator from our repository. However, I never assigned you as the maintainer of this repository. Could you please clarify where you would like to be removed from?

**Comment by anandpanda** [comment]
let me send you a screenshot

**Comment by anandpanda** [comment]
look there, i can see your repo
